apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storage
  # name: azurefile
# provisioner: kubernetes.io/azure-file
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
reclaimPolicy: Delete

